
channels:
  - conda-forge
dependencies:
  - python==3.10
  - jupyterlab-git
  - wget
  - curl
  - ncdu
  - ffmpeg
  - rclone
  - awscli
  - hdf5tools
  - pytables
  - pip
  - pip:
    - git+https://github.com/uw-ssec/braingeneerspy.git#egg=braingeneers[data,iot,analysis,ml,hengenlab]
