name: international-deploy
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - glances
  - wget
  - curl
  - ncdu
  - ffmpeg
  - rclone
  - awscli
  - hdf5tools
  - jupyterlab-git
  - pip
  - pip:
    - --no-cache-dir git+https://github.com/uw-ssec/braingeneerspy.git@update_repo#egg=braingeneers[data,iot,analysis,ml,hengenlab]
